// ************************************************************************** //
// Unit.java - This class is a member of the Counters package, which contains //
//             the class definitions and implementations for objects used to  //
//             to represent the virtual playing pieces in jASL.               //
//                                                                            //
//             NOTE: This program is based on Advanced Squad Leader, a        //
//                   product of The Avalon Hill Game Company.                 //
//                                                                            //
// Written By: Craig R. Campbell  -  December 1998                            //
//                                                                            //
// $Header: /tmp/java/jasl.cvs/jasl/source/jasl/counters/Unit.java,v 1.2 1999/07/10 06:29:51 craig Exp $
// ************************************************************************** //

package Counters;

// ************************************************************************** //
// Unit class - This is the top-level class of the Counter package. All       //
//              the classes in this Package are derived from Unit.            //
// ************************************************************************** //

abstract public class Unit
{
	// Private data members

	// This variable contains a descriptive name for the derived object of this
	// class. It is typically set to the name of the child class being
	// instantiated (ie. "Squad").

	private String description;

	// The following strings are used as messages for any exceptions that may be
	// generated by bad data being passed to the protected constructor.

	private static final String nullPointerError = 
	    "Error: Unit(constructor) - Null parameter received.";
		
	private static final String badArgumentError = 
	    "Error: Unit(constructor) - Invalid parameter received (zero length).";

	// Constructors

	// Default constructor. This is used to create arrays of this data type
	// which can be used to reference groups of objects derived from Unit.

	public Unit() {}
	
	// This constructor is used during the instantiation of classes derived
	// from Unit. The parameter is passed up the chain from the object being
	// created.

	protected Unit(String description)
		throws NullPointerException, IllegalArgumentException
	{
		// Check the input value for any problems and throw the appropriate
		// exception if necessary.

		if (description == null)
		{
			throw new NullPointerException(nullPointerError);
		}

		if (description.length() == 0)
		{
			throw new IllegalArgumentException(badArgumentError);
		}

		// If we got this far, assume that the value is OK and copy it to the
		// local description variable. 

		this.description = description;
	}

	// Public symbolic constants 

	// These constants are used to define the minimum values for some of the
	// key attributes for all of the fighting units defined by the public
	// subclasses of Unit. They are defined as public to allow their values to
	// be accessed without creating an object. A possible application might be
	// in building a menu to create "Unit" objects.

	public static final int MIN_FIREPOWER = 0;
	public static final int MIN_MOVEMENT  = 0;
	public static final int MIN_RANGE     = 0;

	// Protected symbolic constants

	// These constants are available to all subclasses and are used to name
	// public classes of the Counters hierarchy that may be directly 
	// instantiated. These values end up getting sent to this class to become
	// the value of "description".

	protected static final String SQUAD  = "Squad";
	protected static final String LEADER = "Leader";

	// Protected access methods

	// showValues - A function to display the value of the private data members
	//              of the current instance. The intent of this function is to
	//              provide text-based verification output for development and
	//              debugging. This function is only accessible to instances of
	//              the subclasses of Unit and each subclass includes a function
	//              with the same name and purpose. Since this is the top-level
	//              of the hierarchy, this version also includes a header.

	protected void showValues()
	{
		// Display header.

		System.out.println("Counter package instance values:");
		System.out.println("--------------------------------");

		// Display data stored in this class.

		System.out.println("Description\t: " + description);
	}

	// Public access methods

	// getDescription - A function to return the value of the description member
	//                  variable to the calling program.

	public String getDescription()
	{
		return (description);
	}

	// The following abstract methods are defined in the subclasses of Unit.
	// This is necessary in order to allow different types of instances derived
	// from Unit to be stored and accessed as the generic Unit type. It is also
	// necessary in order to access the public access methods without casting to
	// a specific instance type.

	// Fighting.java

	abstract public String getNationality();

	// Mobile.java

	abstract public int getMovement();

	// Infantry.java

	abstract public String getStatus();
	abstract public boolean rally(boolean isLeaderPresent,int modifier);
	abstract public boolean moraleCheck(int modifier);

	// Personnel.java

 	abstract public int getFirepower();
 	abstract public int getNormalRange();

	// Squad.java

	abstract public String getClassification();
	
	// Leader.java

	abstract public int getModifier();
	abstract public String getName();
}
