################################################################################
# Driver.py - This file contains the Driver script, which is used to test the  #
#             functionality of the public <A HREF="http://java.sun.com/">Java</A> classes defined in the <A HREF="jasl/jasl.html">jasl</A>     #
#             package hierarchy, accessed by <A HREF="http://www.python.org/">Python</A> using <A HREF="swig/swig.html">libraries</A> and files  #
#             generated by <A HREF="http://www.swig.org/">SWIG</A>.                                               #
#                                                                              #
#             The <A HREF="http://gcc.gnu.org/onlinedocs/gcj/About-CNI.html#About-CNI">CNI</A> (Compiled Native Interface) <A HREF="http://gcc.gnu.org/onlinedocs/gcj/Invocation.html#Invocation">invocation</A> functions, which  #
#             are required to use the Java classes, are initiated in this      #
#             script by the <A HREF="swig/CniWrapper.swig.html">CniWrapper</A> module. This module also provides       #
#             methods to convert a native string to or from a Java <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html">String</A>.     #
#                                                                              #
# Written By : Craig R. Campbell  -  August 2008                               #
#                                                                              #
# $Id: Driver.py,v 1.2 2009/10/29 23:21:03 campbell Exp $
################################################################################

import sys
sys.path.append("/home/campbell/java/jasl/lib/python")

from CniWrapper import *
from Counters   import *
from Utilities  import *

cni_wrapper = CNI_WRAPPER()

# Test the Dice class.

print "\nTesting the execution of the Dice class:\n";

for i in (list(range(12))):
    dice = Dice()

#   print "White: %d Colored: %d Combined: %2d\n" % \
#         (dice.getWhiteDieValue(),   \
#          dice.getColoredDieValue(), \
#          dice.getCombinedResult())

    print "%s" % (cni_wrapper.stringToConstChar(dice.toString()))
